server:
  port: ${PORT:8081}


spring:
  application:
    name: users_senders-api

  config:
    import: optional:configserver
  cloud:
    config:
      import-check:
        enabled: false

  datasource:
    driver-class-name: org.postgresql.Driver
    # Config para o banco de dados da empresa
    url: jdbc:postgresql://localhost:5432/users_senders
    username: postgres
    password: mon123
    # Fim config banco de dados empresa
    # initialize: true
    maxActivate: 3

    jpa:
      hibernate:
        ddl-auto: create-drop
        format_sql: true
      show_sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL9Dialect
  sql:
    init:
      mode:
      continue-on-error: true
      platform: postgresql