INSERT INTO CATEGORY(ID, DESCRIPTION, TIPO) VALUES (1001,'PAGAMENTO', 'ENTRADA');
INSERT INTO CATEGORY(ID, DESCRIPTION, TIPO) VALUES (1002,'INVESTIMENTO', 'ENTRADA');
INSERT INTO CATEGORY(ID, DESCRIPTION, TIPO) VALUES (1003,'ENERGIA', 'SAIDA');
INSERT INTO CATEGORY(ID, DESCRIPTION, TIPO) VALUES (1004,'AGUA', 'SAIDA');
INSERT INTO CATEGORY(ID, DESCRIPTION, TIPO) VALUES (1005,'FACULDADE', 'SAIDA');


INSERT INTO CREDITS (FK_CATEGORY, ID, VALOR, DATE_IMPORT, DESCRICAO, METODO_PAGAMENTO, TIPO_CREDITO) VALUES (1001, 1001, 4200.00, CURRENT_TIMESTAMP , 'SALARIO MENSAL', 'DEPOSITO', 'MENSAL');
INSERT INTO CREDITS (FK_CATEGORY, ID, VALOR, DATE_IMPORT, DESCRICAO, METODO_PAGAMENTO, TIPO_CREDITO) VALUES (1002, 1001, 100.00, CURRENT_TIMESTAMP , 'INVESTIMENTO NUBANK', 'TRANSFERENCIA', 'BIMESTRAL');

INSERT INTO DEBTS(ID, NOME, VALOR, DATA_VENCIMENTO, DATA_ENTRADA, PARCELAS, QUANTIDADE_PARCELAS, STATUS, TIPO_PAGAMENTO, PLANEJADO, FK_CATEGORY) VALUES (1001, 'AGUA', 800.00, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, FALSE, 1, 'A VENCER', 'DINHEIRO', TRUE, 1003)
INSERT INTO DEBTS(ID, NOME, VALOR, DATA_VENCIMENTO, DATA_ENTRADA, PARCELAS, QUANTIDADE_PARCELAS, STATUS, TIPO_PAGAMENTO, PLANEJADO, FK_CATEGORY) VALUES (1005, 'FACULDADE', 1800.00, '20/12/2023 00:00:00', CURRENT_TIMESTAMP, FALSE, 1, 'A VENCER', 'BOLETO', TRUE, 1005)