INSERT INTO CATEGORY(ID, DESCRIPTION) VALUES (1001,'PAGAMENTO');

INSERT INTO CREDITS (FK_CATEGORY, ID, VALOR, DATE_IMPORT, DESCRICAO, METODO_PAGAMENTO, TIPO_CREDITO) VALUES (1001, 1001, 4200.00, CURRENT_TIMESTAMP , 'SALARIO MENSAL', 'DEPOSITO', 'MENSAL');

